name: Notify Discord (bot)

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      message:
        description: Message to send to Discord
        required: false
        default: "v letter"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord channel
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ vars.DISCORD_CHANNEL_ID }}
          MESSAGE: ${{ github.event.inputs.message }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          set -e
          if [ -z "$TOKEN" ] || [ -z "$CHANNEL_ID" ]; then
            echo "Missing TOKEN or CHANNEL_ID"; exit 1;
          fi
          python3 - << 'PY'
import json, os, urllib.request, pathlib
TOKEN=os.environ['TOKEN']; CHANNEL_ID=os.environ['CHANNEL_ID']
msg=os.environ.get('MESSAGE')
if not msg:
    evt_path=os.environ.get('GITHUB_EVENT_PATH')
    if evt_path and pathlib.Path(evt_path).exists():
        try:
            with open(evt_path,'r') as f: evt=json.load(f)
            msg=evt.get('head_commit',{}).get('message') or 'v letter'
        except Exception:
            msg='v letter'
    else:
        msg='v letter'
req=urllib.request.Request(f'https://discord.com/api/v10/channels/{CHANNEL_ID}/messages',
  data=json.dumps({'content': msg}).encode(),
  headers={'Authorization': f'Bot {TOKEN}','Content-Type':'application/json'})
print(urllib.request.urlopen(req).read().decode())
PY

